import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import Image from "next/image";
import Link from "next/link";
import { currentUser } from "@clerk/nextjs/server";
import { ProfileProvider } from "./context/ProfileContext";
import { Toaster } from "sonner";

const DotIcon = () => {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 512 512"
      fill="currentColor"
    >
      <path d="M256 512A256 256 0 1 0 256 0a256 256 0 1 0 0 512z" />
    </svg>
  );
};

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await currentUser();

  return (
    <ClerkProvider>
      <ProfileProvider>
        <html lang="en">
          <body className="max-w-6xl mx-auto font-sf">
            <header className="flex justify-between items-center px-4 py-6">
              <div className="flex items-center gap-4">
                <Link href="/">
                  <Image src="/logo.png" alt="logo" width={210} height={100} />
                </Link>
              </div>
              <div className="flex items-center gap-4">
                <SignedOut>
                  <SignInButton>
                    <button className="bg-slate-900 text-white px-4 py-2 rounded-md hover:bg-slate-800">
                      ログイン
                    </button>
                  </SignInButton>
                </SignedOut>
                <SignedIn>
                  <UserButton
                    userProfileMode="navigation"
                    userProfileUrl={`/profile/${user?.id}`}
                  />
                </SignedIn>
              </div>
            </header>
            <main className="container flex items-center justify-center mx-auto my-10 px-4 sm:px-8 lg:px-4 max-w-5xl">
              {children}
            </main>
            <Toaster position="bottom-right" />
          </body>
        </html>
      </ProfileProvider>
    </ClerkProvider>
  );
}
